### ISSUE TITLE
IOS with v2ray , killed by memory limit

### ISSUE THREAD

**Issue by excellentconnect** [Jigsaw-Code/outline-go-tun2socks#32]
V2ray:4.20
go-tun2socks: lastest version

**Comment by excellentconnect** [comment]
IOS 11 works well.

IOS12 And IOS 13 both can reproduce simply.

**Comment by alalamav** [comment]
Hi @excellentconnect, we are aware of the iOS memory limits, which is why we set the garbage collector to a one minute interval and set the GC percentage to 10. 
Our team uses this framework on Outline, which relies on Shadowsocks. We have observed some crashes due to hitting the memory limit, but it's not 100% reproducible. Perhaps you can optimize the vray implementation?

**Comment by ednew2018** [comment]
@alalamav Is it possible to make GO GC even more aggressive. Like calling freeOfMemory every 30 seconds or 10 seconds?

**Comment by bemasc** [comment]
It's possible, but (if everything is working correctly) it can't save more than 10% of memory.

If you're interested in improving memory usage, a good first step would be to write out a [memory profile](https://golang.org/pkg/runtime/pprof/) and identify what is taking up the most space.

**Comment by IT85626508** [comment]
The server needs to verify the user information, how to pass the user information to the server when using Tun2socks.framework?

**Comment by fortuna** [comment]
Since this bug was filed we made a number of memory improvements. Please reopen with fresh information if it's still an issue.
